<?php
$content = "<html>\n";
$content .= "<head>\n";
$content .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n";
$content .= "<meta name='viewport' content='width=device-width, initial-scale=1.0' />\n";
$content .= "<title>$subject</title>\n";
$content .= "</head>\n";
$content .= "<body bgcolor='#fbfdfd'>\n";
$content .= "<table border='0' cellspacing='0' cellpadding='0' width='100%' height='auto' bgcolor='#fbfdfd'><tr>\n";
$content .= "<td align='center'>\n";
$content .= "<table align='center' border='0' cellspacing='0' cellpadding='0'><tr>\n";
$content .= "<td align='center' valign='top' style='font-family:Verdana, Geneva, sans-serif;font-size:10px;line-height:18px;color:#000000;'><span style='color:#000000; font-size: 10px;'>".$locale['nl_913']."</span><br><br></td></tr>\n";
$content .= "<tr><td align='center' valign='top' style='font-family:Verdana, Geneva, sans-serif;font-size:13px;line-height:18px;'>\n";
$content .= "<a style='color: #000099;' $archive_bit</a>\n";
$content .= "<br><br></td></tr></table>\n";
$content .= "<table border='0' cellspacing='0' cellpadding='0' width='600' align='center' bgcolor='#fbfdfd'><tr>\n";
$content .= "<td align='center'><table bgcolor='#ffffff' border='0' cellspacing='0' cellpadding='0' width='100%'><tr>\n";
$content .= "<td width='600' height='72' background='".$settings['siteurl']."infusions/news_letter_panel/images/tmpl01/header.gif' alt='' border='0' style='display: block;'></td></tr>\n";
$content .= "<tr><td align='center' background='".$settings['siteurl']."infusions/news_letter_panel/images/tmpl01/mid.gif' alt='' border='0' style='display: block;'>\n";
$content .= "<br><br><span style='font-family:Verdana, Geneva, sans-serif;font-size:22px;line-height:18px;color:#0000aa;'><b>".$settings['sitename']."</b></span><br><br></td></tr><tr>\n";
$content .= "<td align='center' background='".$settings['siteurl']."infusions/news_letter_panel/images/tmpl01/mid.gif' alt='' border='0' style='display: block;'><span style='font-family:Verdana, Geneva, sans-serif;font-size:18px;line-height:18px;color:#004000;'><b>$news_head</b></span><br><br>\n";
$content .= "<table width='560'><td align='right' style='font-family:Verdana, Geneva, sans-serif;font-size:9px;line-height:18px;color:#000000;'><span style='color:#000000; font-size: 9px;'><b>".$locale['nl_112']." $send_date</b></span></td></tr>\n";
$content .= "<tr><td width='100%' height='1'><hr /></td></tr></table></td></tr><tr>\n";
$content .= "<td align='center' background='".$settings['siteurl']."infusions/news_letter_panel/images/tmpl01/mid.gif' alt='' border='0' style='display: block;'>\n";
$content .= "<table align='center' width='92%' border='0' cellpadding='0' cellspacing='0'><tr>\n";
$content .= "<td align='left' style='font-family:Verdana, Geneva, sans-serif;font-size:13px;line-height:18px;color:#000000;'><span style='color:#000000; font-size: 13px;'>$usrtxt</span></td>\n";
$content .= "</tr></table></td></tr><tr>\n";
$content .= "<td align='center' background='".$settings['siteurl']."infusions/news_letter_panel/images/tmpl01/mid.gif' alt='' border='0' style='display: block;'>\n";
$content .= "<table width='560' align='center'><tr><td width='100%' height='1'><hr /></td></tr><tr><td align='center' valign='top'>\n";
$content .= "<span style='color:#000000; font-size: 11px;'>".$locale['nl_920']."</span><a style='color: #0000dd;' href='mailto:".$settings['siteemail']."'><span style='color:#0000dd; font-size: 11px;'>".$locale['nl_923']."</span></a><span style='color:#000000; font-size: 11px;'>".$locale['nl_921']."</span></td>\n";
$content .= "</tr></table><br><span style='color:#000000; font-size: 11px;'>".$locale['nl_900']." ".$settings['sitename']."<br>".$locale['nl_924']."</span><a style='color: #0000dd;' href='".$settings['siteurl']."'><span style='color:#0000dd; font-size: 11px;'>".$settings['siteurl']."</span></a>\n";
$content .= "<span style='color:#000000; font-size: 11px;'>".$locale['nl_901']."</span></td>\n";
$content .= "</tr><tr>\n";
$content .= "<td align='center' valign='top' width='600' height='72' background='".$settings['siteurl']."infusions/news_letter_panel/images/tmpl01/footer.gif' alt='' border='0' style='display: block;'></td></tr></table>\n";
$content .= "</td></tr></table>\n";
$content .= "<table align='center' border='0' cellspacing='0' cellpadding='0'><tr><td align='center' style='font-family:Verdana, Geneva, sans-serif;font-size:11px;line-height:18px;color:#000000;'><br><br><span style='color:#000000; font-size: 11px;'>".$locale['nl_902']."</span><br><br>\n";
$content .= "<a style='color: #000099;' href='".$settings['siteurl']."infusions/news_letter_panel/unsubscribe.php'><span style='color:#000099; font-size: 11px;'>".$locale['nl_903']."</span></a><br><br>\n";
$content .= " <a style='color: #000099;' href='".$settings['siteurl']."privacy_policy.php'><span style='color:#000099; font-size: 11px;'>".$locale['nl_904']."</span></a>\n";
$content .= "<br><br></td></tr></table>\n";
$content .= "</td></tr></table>\n";
$content .= "</body></html>\n";
?>